const cityOptions = [
  { value: "Select a City", label: "Select a City" },
  { value: "Adilabad", label: "Adilabad" },
  { value: "Agra", label: "Agra" },
  { value: "Ahmedabad", label: "Ahmedabad" },
  { value: "Ahmednagar", label: "Ahmednagar" },
  { value: "Aizawl", label: "Aizawl" },
  { value: "Ajitgarh (Mohali)", label: "Ajitgarh (Mohali)" },
  { value: "Ajmer", label: "Ajmer" },
  { value: "Akola", label: "Akola" },
  { value: "Alappuzha", label: "Alappuzha" },
  { value: "Aligarh", label: "Aligarh" },
  { value: "Alirajpur", label: "Alirajpur" },
  { value: "Allahabad", label: "Allahabad" },
  { value: "Almora", label: "Almora" },
  { value: "Alwar", label: "Alwar" },
  { value: "Ambala", label: "Ambala" },
  { value: "Ambedkar Nagar", label: "Ambedkar Nagar" },
  { value: "Amravati", label: "Amravati" },
  { value: "Amreli district", label: "Amreli district" },
  { value: "Amritsar", label: "Amritsar" },
  { value: "Anand", label: "Anand" },
  { value: "Anantapur", label: "Anantapur" },
  { value: "Anantnag", label: "Anantnag" },
  { value: "Angul", label: "Angul" },
  { value: "Anjaw", label: "Anjaw" },
  { value: "Anuppur", label: "Anuppur" },
  { value: "Araria", label: "Araria" },
  { value: "Ariyalur", label: "Ariyalur" },
  { value: "Arwal", label: "Arwal" },
  { value: "Ashok Nagar", label: "Ashok Nagar" },
  { value: "Auraiya", label: "Auraiya" },
  { value: "Aurangabad", label: "Aurangabad" },
  { value: "Aurangabad", label: "Aurangabad" },
  { value: "Azamgarh", label: "Azamgarh" },
  { value: "Badgam", label: "Badgam" },
  { value: "Bagalkot", label: "Bagalkot" },
  { value: "Bageshwar", label: "Bageshwar" },
  { value: "Bagpat", label: "Bagpat" },
  { value: "Bahraich", label: "Bahraich" },
  { value: "Baksa", label: "Baksa" },
  { value: "Balaghat", label: "Balaghat" },
  { value: "Balangir", label: "Balangir" },
  { value: "Balasore", label: "Balasore" },
  { value: "Ballia", label: "Ballia" },
  { value: "Balrampur", label: "Balrampur" },
  { value: "Banaskantha", label: "Banaskantha" },
  { value: "Banda", label: "Banda" },
  { value: "Bandipora", label: "Bandipora" },
  { value: "Bangalore Rural", label: "Bangalore Rural" },
  { value: "Bangalore Urban", label: "Bangalore Urban" },
  { value: "Banka", label: "Banka" },
  { value: "Bankura", label: "Bankura" },
  { value: "Banswara", label: "Banswara" },
  { value: "Barabanki", label: "Barabanki" },
  { value: "Baramulla", label: "Baramulla" },
  { value: "Baran", label: "Baran" },
  { value: "Bardhaman", label: "Bardhaman" },
  { value: "Bareilly", label: "Bareilly" },
  { value: "Bargarh (Baragarh)", label: "Bargarh (Baragarh)" },
  { value: "Barmer", label: "Barmer" },
  { value: "Barnala", label: "Barnala" },
  { value: "Barpeta", label: "Barpeta" },
  { value: "Barwani", label: "Barwani" },
  { value: "Bastar", label: "Bastar" },
  { value: "Basti", label: "Basti" },
  { value: "Bathinda", label: "Bathinda" },
  { value: "Beed", label: "Beed" },
  { value: "Begusarai", label: "Begusarai" },
  { value: "Belgaum", label: "Belgaum" },
  { value: "Bellary", label: "Bellary" },
  { value: "Betul", label: "Betul" },
  { value: "Bhadrak", label: "Bhadrak" },
  { value: "Bhagalpur", label: "Bhagalpur" },
  { value: "Bhandara", label: "Bhandara" },
  { value: "Bharatpur", label: "Bharatpur" },
  { value: "Bharuch", label: "Bharuch" },
  { value: "Bhavnagar", label: "Bhavnagar" },
  { value: "Bhilwara", label: "Bhilwara" },
  { value: "Bhind", label: "Bhind" },
  { value: "Bhiwani", label: "Bhiwani" },
  { value: "Bhojpur", label: "Bhojpur" },
  { value: "Bhopal", label: "Bhopal" },
  { value: "Bidar", label: "Bidar" },
  { value: "Bijapur", label: "Bijapur" },
  { value: "Bijapur", label: "Bijapur" },
  { value: "Bijnor", label: "Bijnor" },
  { value: "Bikaner", label: "Bikaner" },
  { value: "Bilaspur", label: "Bilaspur" },
  { value: "Bilaspur", label: "Bilaspur" },
  { value: "Birbhum", label: "Birbhum" },
  { value: "Bishnupur", label: "Bishnupur" },
  { value: "Bokaro", label: "Bokaro" },
  { value: "Bongaigaon", label: "Bongaigaon" },
  { value: "Boudh (Bauda)", label: "Boudh (Bauda)" },
  { value: "Budaun", label: "Budaun" },
  { value: "Bulandshahr", label: "Bulandshahr" },
  { value: "Buldhana", label: "Buldhana" },
  { value: "Bundi", label: "Bundi" },
  { value: "Burhanpur", label: "Burhanpur" },
  { value: "Buxar", label: "Buxar" },
  { value: "Cachar", label: "Cachar" },
  { value: "Central Delhi", label: "Central Delhi" },
  { value: "Chamarajnagar", label: "Chamarajnagar" },
  { value: "Chamba", label: "Chamba" },
  { value: "Chamoli", label: "Chamoli" },
  { value: "Champawat", label: "Champawat" },
  { value: "Champhai", label: "Champhai" },
  { value: "Chandauli", label: "Chandauli" },
  { value: "Chandel", label: "Chandel" },
  { value: "Chandigarh", label: "Chandigarh" },
  { value: "Chandrapur", label: "Chandrapur" },
  { value: "Changlang", label: "Changlang" },
  { value: "Chatra", label: "Chatra" },
  { value: "Chennai", label: "Chennai" },
  { value: "Chhatarpur", label: "Chhatarpur" },
  {
    value: "Chhatrapati Shahuji Maharaj Nagar",
    label: "Chhatrapati Shahuji Maharaj Nagar",
  },
  { value: "Chhindwara", label: "Chhindwara" },
  { value: "Chikkaballapur", label: "Chikkaballapur" },
  { value: "Chikkamagaluru", label: "Chikkamagaluru" },
  { value: "Chirang", label: "Chirang" },
  { value: "Chitradurga", label: "Chitradurga" },
  { value: "Chitrakoot", label: "Chitrakoot" },
  { value: "Chittoor", label: "Chittoor" },
  { value: "Chittorgarh", label: "Chittorgarh" },
  { value: "Churachandpur", label: "Churachandpur" },
  { value: "Churu", label: "Churu" },
  { value: "Coimbatore", label: "Coimbatore" },
  { value: "Cooch Behar", label: "Cooch Behar" },
  { value: "Cuddalore", label: "Cuddalore" },
  { value: "Cuttack", label: "Cuttack" },
  { value: "Dadra and Nagar Haveli", label: "Dadra and Nagar Haveli" },
  { value: "Dahod", label: "Dahod" },
  { value: "Dakshin Dinajpur", label: "Dakshin Dinajpur" },
  { value: "Dakshina Kannada", label: "Dakshina Kannada" },
  { value: "Daman", label: "Daman" },
  { value: "Damoh", label: "Damoh" },
  { value: "Dantewada", label: "Dantewada" },
  { value: "Darbhanga", label: "Darbhanga" },
  { value: "Darjeeling", label: "Darjeeling" },
  { value: "Darrang", label: "Darrang" },
  { value: "Datia", label: "Datia" },
  { value: "Dausa", label: "Dausa" },
  { value: "Davanagere", label: "Davanagere" },
  { value: "Debagarh (Deogarh)", label: "Debagarh (Deogarh)" },
  { value: "Dehradun", label: "Dehradun" },
  { value: "Deoghar", label: "Deoghar" },
  { value: "Deoria", label: "Deoria" },
  { value: "Dewas", label: "Dewas" },
  { value: "Dhalai", label: "Dhalai" },
  { value: "Dhamtari", label: "Dhamtari" },
  { value: "Dhanbad", label: "Dhanbad" },
  { value: "Dhar", label: "Dhar" },
  { value: "Dharmapuri", label: "Dharmapuri" },
  { value: "Dharwad", label: "Dharwad" },
  { value: "Dhemaji", label: "Dhemaji" },
  { value: "Dhenkanal", label: "Dhenkanal" },
  { value: "Dholpur", label: "Dholpur" },
  { value: "Dhubri", label: "Dhubri" },
  { value: "Dhule", label: "Dhule" },
  { value: "Dibang Valley", label: "Dibang Valley" },
  { value: "Dibrugarh", label: "Dibrugarh" },
  { value: "Dima Hasao", label: "Dima Hasao" },
  { value: "Dimapur", label: "Dimapur" },
  { value: "Dindigul", label: "Dindigul" },
  { value: "Dindori", label: "Dindori" },
  { value: "Diu", label: "Diu" },
  { value: "Doda", label: "Doda" },
  { value: "Dumka", label: "Dumka" },
  { value: "Dungapur", label: "Dungapur" },
  { value: "Durg", label: "Durg" },
  { value: "East Champaran", label: "East Champaran" },
  { value: "East Delhi", label: "East Delhi" },
  { value: "East Garo Hills", label: "East Garo Hills" },
  { value: "East Khasi Hills", label: "East Khasi Hills" },
  { value: "East Siang", label: "East Siang" },
  { value: "East Sikkim", label: "East Sikkim" },
  { value: "East Singhbhum", label: "East Singhbhum" },
  { value: "Eluru", label: "Eluru" },
  { value: "Ernakulam", label: "Ernakulam" },
  { value: "Erode", label: "Erode" },
  { value: "Etah", label: "Etah" },
  { value: "Etawah", label: "Etawah" },
  { value: "Faizabad", label: "Faizabad" },
  { value: "Faridabad", label: "Faridabad" },
  { value: "Faridkot", label: "Faridkot" },
  { value: "Farrukhabad", label: "Farrukhabad" },
  { value: "Fatehabad", label: "Fatehabad" },
  { value: "Fatehgarh Sahib", label: "Fatehgarh Sahib" },
  { value: "Fatehpur", label: "Fatehpur" },
  { value: "Fazilka", label: "Fazilka" },
  { value: "Firozabad", label: "Firozabad" },
  { value: "Firozpur", label: "Firozpur" },
  { value: "Gadag", label: "Gadag" },
  { value: "Gadchiroli", label: "Gadchiroli" },
  { value: "Gajapati", label: "Gajapati" },
  { value: "Ganderbal", label: "Ganderbal" },
  { value: "Gandhinagar", label: "Gandhinagar" },
];

export default cityOptions;
